install:
  - choco install gitversion.portable -pre -y
configuration: Release
assembly_info:
  patch: false

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build:
  project: DirectAdmin.sln

artifacts:
- path: DirectAdmin.Client\bin\Release\DirectAdmin.Client.dll
  name: DirectAdmin.Client.dll
- path: DirectAdmin.Client\bin\Release\DirectAdmin.Client.xml
  name: DirectAdmin.Client.xml
- path: '**\DirectAdmin.Client.*.nupkg'

after_build:
  - cmd: ECHO nuget pack DirectAdmin.Client\DirectAdmin.Client.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: nuget pack DirectAdmin.Client\DirectAdmin.Client.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"

deploy:
  provider: NuGet
  api_key:
    secure: 0qbuPrrnu/qrD5eHEA3maAR7qt6Vg9oOfaoYtqWzcjZNSxoaZYqx+1gztJml805p
  skip_symbols: false
  artifact: /.*\.nupkg/
